// THIS FILE IS AUTOMATICALLY GENERATED AND SHOULD NOT BE EDITED MANUALLY!

namespace Roblox.PluginClasses;
public static class Services
{
	public static extern CoreGui CoreGui { get; }
	public static extern ChangeHistoryService ChangeHistoryService { get; }
	public static extern DebuggerManager DebuggerManager { get; }
	public static extern NetworkSettings NetworkSettings { get; }
	public static extern PackageService PackageService { get; }
	public static extern PluginDebugService PluginDebugService { get; }
	public static extern PluginGuiService PluginGuiService { get; }
	public static extern RenderSettings RenderSettings { get; }
	public static extern RobloxPluginGuiService RobloxPluginGuiService { get; }
	public static extern Selection Selection { get; }
	public static extern StudioData StudioData { get; }
	public static extern StudioService StudioService { get; }
	public static extern TaskScheduler TaskScheduler { get; }
	public static extern TestService TestService { get; }
	public static extern VersionControlService VersionControlService { get; }
}

// GENERATED ROBLOX INSTANCE CLASSES

public interface Object;
public interface VideoCapture : Capture;
public interface ConfigSnapshot : Object;
public interface EditableImage : Object;
public interface EditableMesh : Object;
public partial interface Instance : Object
{
	public string GetDebugId(int? scopeLength = null);
}

public interface AccessoryDescription : ICreatableInstance
{
	public new AccessoryDescription Clone();
}

public interface AccountService : IServiceInstance
{
	public new AccountService Clone();
}

public interface Accoutrement : ICreatableInstance
{
	public new Accoutrement Clone();
}

public interface Accessory : Accoutrement, ICreatableInstance;
public interface AchievementService : IServiceInstance
{
	public new AchievementService Clone();
}

public interface ActivityHistoryEventService : IServiceInstance
{
	public new ActivityHistoryEventService Clone();
}

public interface AdPortal : ICreatableInstance
{
	public new AdPortal Clone();
}

public interface AnalyticsService : IServiceInstance
{
	public new AnalyticsService Clone();
}

public interface Animation : ICreatableInstance
{
	public new Animation Clone();
}

public interface AnimationClip : Instance
{
	public new AnimationClip Clone();
}

public partial interface KeyframeSequence : AnimationClip, ICreatableInstance;
public partial interface AnimationClipProvider : IServiceInstance
{
	public new AnimationClipProvider Clone();
	public AnimationClip GetAnimationClip(string assetId);
	public AnimationClip GetAnimationClipById(long assetId, bool useCache);
}

public interface AnimationController : ICreatableInstance
{
	public new AnimationController Clone();
}

public interface AnimationFromVideoCreatorService : IServiceInstance
{
	public new AnimationFromVideoCreatorService Clone();
}

public interface AnimationFromVideoCreatorStudioService : IServiceInstance
{
	public new AnimationFromVideoCreatorStudioService Clone();
}

public interface AnimationRigData : ICreatableInstance
{
	public new AnimationRigData Clone();
}

public interface AnimationStreamTrack : Instance
{
	public new AnimationStreamTrack Clone();
}

public interface AnimationTrack : Instance
{
	public new AnimationTrack Clone();
}

public partial interface Animator : ICreatableInstance
{
	public new Animator Clone();
	public void StepAnimations(float deltaTime);
}

public interface Annotation : ICreatableInstance
{
	public new Annotation Clone();
}

public interface WorkspaceAnnotation : Annotation, ICreatableInstance;
public interface AnnotationsService : IServiceInstance
{
	public new AnnotationsService Clone();
}

public interface AppLifecycleObserverService : IServiceInstance
{
	public new AppLifecycleObserverService Clone();
}

public interface AppUpdateService : IServiceInstance
{
	public new AppUpdateService Clone();
}

public interface AssetDeliveryProxy : IServiceInstance
{
	public new AssetDeliveryProxy Clone();
}

public interface AssetImportService : IServiceInstance
{
	public new AssetImportService Clone();
}

public interface AssetManagerService : IServiceInstance
{
	public new AssetManagerService Clone();
}

public interface AssetPatchSettings : Instance
{
	public new AssetPatchSettings Clone();
}

public partial interface AssetService : IServiceInstance
{
	public new AssetService Clone();
}

public interface Atmosphere : ICreatableInstance
{
	public new Atmosphere Clone();
}

public interface Attachment : ICreatableInstance
{
	public new Attachment Clone();
}

public interface Bone : Attachment, ICreatableInstance;
public interface AudioAnalyzer : ICreatableInstance
{
	public new AudioAnalyzer Clone();
}

public interface AudioChannelMixer : ICreatableInstance
{
	public new AudioChannelMixer Clone();
}

public interface AudioChannelSplitter : ICreatableInstance
{
	public new AudioChannelSplitter Clone();
}

public interface AudioChorus : ICreatableInstance
{
	public new AudioChorus Clone();
}

public interface AudioCompressor : ICreatableInstance
{
	public new AudioCompressor Clone();
}

public interface AudioDeviceInput : ICreatableInstance
{
	public new AudioDeviceInput Clone();
}

public interface AudioDeviceOutput : ICreatableInstance
{
	public new AudioDeviceOutput Clone();
}

public interface AudioDistortion : ICreatableInstance
{
	public new AudioDistortion Clone();
}

public interface AudioEcho : ICreatableInstance
{
	public new AudioEcho Clone();
}

public interface AudioEmitter : ICreatableInstance
{
	public new AudioEmitter Clone();
}

public interface AudioEqualizer : ICreatableInstance
{
	public new AudioEqualizer Clone();
}

public interface AudioFader : ICreatableInstance
{
	public new AudioFader Clone();
}

public interface AudioFilter : ICreatableInstance
{
	public new AudioFilter Clone();
}

public interface AudioFlanger : ICreatableInstance
{
	public new AudioFlanger Clone();
}

public interface AudioFocusService : IServiceInstance
{
	public new AudioFocusService Clone();
}

public interface AudioLimiter : ICreatableInstance
{
	public new AudioLimiter Clone();
}

public interface AudioListener : ICreatableInstance
{
	public new AudioListener Clone();
}

public interface AudioPitchShifter : ICreatableInstance
{
	public new AudioPitchShifter Clone();
}

public interface AudioPlayer : ICreatableInstance
{
	public new AudioPlayer Clone();
}

public interface AudioRecorder : ICreatableInstance
{
	public new AudioRecorder Clone();
}

public interface AudioReverb : ICreatableInstance
{
	public new AudioReverb Clone();
}

public interface AudioSearchParams : ICreatableInstance
{
	public new AudioSearchParams Clone();
}

public interface AudioTextToSpeech : ICreatableInstance
{
	public new AudioTextToSpeech Clone();
}

public interface AuroraScriptObject : Instance
{
	public new AuroraScriptObject Clone();
}

public interface AuroraScriptService : IServiceInstance
{
	public new AuroraScriptService Clone();
}

public interface AuroraService : IServiceInstance
{
	public new AuroraService Clone();
}

public interface AvatarAccessoryRules : ICreatableInstance
{
	public new AvatarAccessoryRules Clone();
}

public interface AvatarAnimationRules : ICreatableInstance
{
	public new AvatarAnimationRules Clone();
}

public interface AvatarBodyRules : ICreatableInstance
{
	public new AvatarBodyRules Clone();
}

public interface AvatarChatService : IServiceInstance
{
	public new AvatarChatService Clone();
}

public interface AvatarClothingRules : ICreatableInstance
{
	public new AvatarClothingRules Clone();
}

public interface AvatarCollisionRules : ICreatableInstance
{
	public new AvatarCollisionRules Clone();
}

public interface AvatarCreationService : IServiceInstance
{
	public new AvatarCreationService Clone();
}

public interface AvatarEditorService : IServiceInstance
{
	public new AvatarEditorService Clone();
}

public interface AvatarImportService : IServiceInstance
{
	public new AvatarImportService Clone();
}

public interface AvatarPreloader : IServiceInstance
{
	public new AvatarPreloader Clone();
}

public interface AvatarRules : ICreatableInstance
{
	public new AvatarRules Clone();
}

public interface AvatarSettings : IServiceInstance
{
	public new AvatarSettings Clone();
}

public interface BadgeService : IServiceInstance
{
	public new BadgeService Clone();
}

public interface BaseImportData : Instance
{
	public new BaseImportData Clone();
}

public interface GroupImportData : BaseImportData;
public interface MaterialImportData : BaseImportData;
public interface MeshImportData : BaseImportData;
public interface RootImportData : BaseImportData;
public interface BasePlayerGui : Instance
{
	public new BasePlayerGui Clone();
}

public interface CoreGui : BasePlayerGui, IServiceInstance
{
	public int Version { get; }
}

public partial interface PlayerGui : BasePlayerGui;
public partial interface StarterGui : BasePlayerGui, IServiceInstance
{
	public bool ShowDevelopmentGui { get; set; }
}

public interface BaseWrap : Instance
{
	public new BaseWrap Clone();
}

public interface WrapDeformer : BaseWrap, ICreatableInstance;
public interface WrapLayer : BaseWrap, ICreatableInstance;
public interface WrapTarget : BaseWrap, ICreatableInstance;
public interface Beam : ICreatableInstance
{
	public new Beam Clone();
}

public interface BindableEvent : ICreatableInstance
{
	public new BindableEvent Clone();
}

public interface BindableFunction : ICreatableInstance
{
	public new BindableFunction Clone();
}

public interface BodyAngularVelocity : BodyMover, ICreatableInstance;
public interface BodyForce : BodyMover, ICreatableInstance;
public interface BodyGyro : BodyMover, ICreatableInstance;
public interface BodyPosition : BodyMover, ICreatableInstance;
public interface BodyThrust : BodyMover, ICreatableInstance;
public interface BodyVelocity : BodyMover, ICreatableInstance;
public interface RocketPropulsion : BodyMover, ICreatableInstance;
public interface BodyPartDescription : ICreatableInstance
{
	public new BodyPartDescription Clone();
}

public interface Breakpoint : ICreatableInstance
{
	public new Breakpoint Clone();
}

public interface BugReporterService : IServiceInstance
{
	public new BugReporterService Clone();
}

public interface BulkImportService : IServiceInstance
{
	public new BulkImportService Clone();
}

public interface CalloutService : IServiceInstance
{
	public new CalloutService Clone();
}

public interface CaptureService : IServiceInstance
{
	public new CaptureService Clone();
}

public interface ChangeHistoryService : IServiceInstance
{
	public new ChangeHistoryService Clone();
	public void FinishRecording(string identifier, Enum.FinishRecordingOperation operation, object? finalOptions = null);
	public object GetCanRedo();
	public object GetCanUndo();
	public bool IsRecordingInProgress(string? identifier = null);
	public void Redo();
	public void ResetWaypoints();
	public void SetEnabled(bool state);
	public void SetWaypoint(string name);
	public string? TryBeginRecording(string name, string? displayName = null);
	public void Undo();
	public delegate void OnRecordingFinishedDelegate(string name, string? displayName, string? identifier, Enum.FinishRecordingOperation operation, object? finalOptions);
	public event OnRecordingFinishedDelegate OnRecordingFinished;
	public delegate void OnRecordingStartedDelegate(string name, string? displayName);
	public event OnRecordingStartedDelegate OnRecordingStarted;
	public delegate void OnRedoDelegate(string waypoint);
	public event OnRedoDelegate OnRedo;
	public delegate void OnUndoDelegate(string waypoint);
	public event OnUndoDelegate OnUndo;
}

public interface BodyColors : CharacterAppearance, ICreatableInstance;
public interface CharacterMesh : CharacterAppearance, ICreatableInstance;
public interface Clothing : CharacterAppearance;
public interface Pants : Clothing, ICreatableInstance;
public interface Shirt : Clothing, ICreatableInstance;
public interface ShirtGraphic : CharacterAppearance, ICreatableInstance;
public interface Chat : IServiceInstance
{
	public new Chat Clone();
}

public interface ChatbotUIService : IServiceInstance
{
	public new ChatbotUIService Clone();
}

public interface ClickDetector : ICreatableInstance
{
	public new ClickDetector Clone();
}

public interface DragDetector : ClickDetector, ICreatableInstance;
public interface Clouds : ICreatableInstance
{
	public new Clouds Clone();
}

public interface Collaborator : Instance
{
	public new Collaborator Clone();
}

public interface CollaboratorsService : IServiceInstance
{
	public new CollaboratorsService Clone();
}

public interface CollectionService : IServiceInstance
{
	public new CollectionService Clone();
}

public interface CommandInstance : Instance
{
	public new CommandInstance Clone();
}

public interface CommandService : IServiceInstance
{
	public new CommandService Clone();
}

public interface CommerceService : IServiceInstance
{
	public new CommerceService Clone();
}

public interface ConfigService : IServiceInstance
{
	public new ConfigService Clone();
}

public interface ConnectivityService : IServiceInstance
{
	public new ConnectivityService Clone();
}

public interface Constraint : Instance
{
	public new Constraint Clone();
}

public interface AlignOrientation : Constraint, ICreatableInstance;
public interface AlignPosition : Constraint, ICreatableInstance;
public interface AngularVelocity : Constraint, ICreatableInstance;
public interface AnimationConstraint : Constraint, ICreatableInstance;
public interface BallSocketConstraint : Constraint, ICreatableInstance;
public interface HingeConstraint : Constraint, ICreatableInstance;
public interface LineForce : Constraint, ICreatableInstance;
public interface LinearVelocity : Constraint, ICreatableInstance;
public interface RodConstraint : Constraint, ICreatableInstance;
public interface RopeConstraint : Constraint, ICreatableInstance;
public interface SlidingBallConstraint : Constraint;
public interface CylindricalConstraint : SlidingBallConstraint, ICreatableInstance;
public interface SpringConstraint : Constraint, ICreatableInstance;
public interface Torque : Constraint, ICreatableInstance;
public interface TorsionSpringConstraint : Constraint, ICreatableInstance;
public interface UniversalConstraint : Constraint, ICreatableInstance;
public interface VectorForce : Constraint, ICreatableInstance;
public interface ContentProvider : IServiceInstance
{
	public new ContentProvider Clone();
}

public interface ContextActionService : IServiceInstance
{
	public new ContextActionService Clone();
}

public interface Controller : Instance
{
	public new Controller Clone();
}

public interface SkateboardController : Controller, ICreatableInstance;
public interface ControllerBase : Instance
{
	public new ControllerBase Clone();
}

public interface AirController : ControllerBase, ICreatableInstance;
public interface ClimbController : ControllerBase, ICreatableInstance;
public interface GroundController : ControllerBase, ICreatableInstance;
public interface SwimController : ControllerBase, ICreatableInstance;
public interface ControllerManager : ICreatableInstance
{
	public new ControllerManager Clone();
}

public interface ConversationalAIAcceptanceService : IServiceInstance
{
	public new ConversationalAIAcceptanceService Clone();
}

public interface CreatorStoreService : IServiceInstance
{
	public new CreatorStoreService Clone();
}

public interface CrossDMScriptChangeListener : IServiceInstance
{
	public new CrossDMScriptChangeListener Clone();
}

public interface CustomLog : ICreatableInstance
{
	public new CustomLog Clone();
}

public interface DataModelMesh : Instance
{
	public new DataModelMesh Clone();
}

public interface BevelMesh : DataModelMesh;
public interface FileMesh : DataModelMesh, ICreatableInstance;
public interface SpecialMesh : FileMesh, ICreatableInstance;
public interface DataModelPatchService : IServiceInstance
{
	public new DataModelPatchService Clone();
}

public interface DataModelSession : Instance
{
	public new DataModelSession Clone();
}

public interface DataStoreGetOptions : ICreatableInstance
{
	public new DataStoreGetOptions Clone();
}

public interface DataStoreIncrementOptions : ICreatableInstance
{
	public new DataStoreIncrementOptions Clone();
}

public interface DataStoreInfo : Instance
{
	public new DataStoreInfo Clone();
}

public interface DataStoreKey : Instance
{
	public new DataStoreKey Clone();
}

public interface DataStoreKeyInfo : Instance
{
	public new DataStoreKeyInfo Clone();
}

public interface DataStoreObjectVersionInfo : Instance
{
	public new DataStoreObjectVersionInfo Clone();
}

public interface DataStoreOptions : ICreatableInstance
{
	public new DataStoreOptions Clone();
}

public partial interface DataStoreService : IServiceInstance
{
	public new DataStoreService Clone();
}

public interface DataStoreSetOptions : ICreatableInstance
{
	public new DataStoreSetOptions Clone();
}

public interface Debris : IServiceInstance
{
	public new Debris Clone();
}

public interface DebugSettings : Instance
{
	public new DebugSettings Clone();
	public int DataModel { get; }
	public int InstanceCount { get; }
	public bool IsScriptStackTracingEnabled { get; set; }
	public int JobCount { get; }
	public int PlayerCount { get; }
	public bool ReportSoundWarnings { get; set; }
	public string RobloxVersion { get; }
	public Enum.TickCountSampleMethod TickCountPreciseOverride { get; set; }
}

public interface DebuggerBreakpoint : Instance
{
	public new DebuggerBreakpoint Clone();
	public string Condition { get; set; }
	public bool ContinueExecution { get; set; }
	public bool IsEnabled { get; set; }
	public int Line { get; }
	public string LogExpression { get; set; }
	public bool isContextDependentBreakpoint { get; set; }
}

public interface DebuggerConnection : Instance
{
	public new DebuggerConnection Clone();
}

public interface DebuggerConnectionManager : IServiceInstance
{
	public new DebuggerConnectionManager Clone();
}

public interface DebuggerLuaResponse : Instance
{
	public new DebuggerLuaResponse Clone();
}

public interface DebuggerManager : IServiceInstance
{
	public new DebuggerManager Clone();
	public bool DebuggingEnabled { get; }
	public Instance AddDebugger(LuaSourceContainer script);
	public Instance[] GetDebuggers();
	public void Resume();
	public void StepIn();
	public void StepOut();
	public void StepOver();
	public delegate void DebuggerAddedDelegate(Instance debug);
	public event DebuggerAddedDelegate DebuggerAdded;
	public delegate void DebuggerRemovedDelegate(Instance debug);
	public event DebuggerRemovedDelegate DebuggerRemoved;
}

public interface DebuggerUIService : IServiceInstance
{
	public new DebuggerUIService Clone();
}

public interface DebuggerVariable : Instance
{
	public new DebuggerVariable Clone();
}

public interface DebuggerWatch : Instance
{
	public new DebuggerWatch Clone();
	public string Expression { get; set; }
}

public interface DeviceIdService : IServiceInstance
{
	public new DeviceIdService Clone();
}

public interface Dialog : ICreatableInstance
{
	public new Dialog Clone();
}

public interface DialogChoice : ICreatableInstance
{
	public new DialogChoice Clone();
}

public interface Dragger : ICreatableInstance
{
	public new Dragger Clone();
}

public interface DraggerService : IServiceInstance
{
	public new DraggerService Clone();
}

public interface EditableService : IServiceInstance
{
	public new EditableService Clone();
}

public interface EulerRotationCurve : ICreatableInstance
{
	public new EulerRotationCurve Clone();
}

public interface EventIngestService : IServiceInstance
{
	public new EventIngestService Clone();
}

public interface ExampleService : IServiceInstance
{
	public new ExampleService Clone();
}

public interface ExperienceAuthService : IServiceInstance
{
	public new ExperienceAuthService Clone();
}

public interface ExperienceInviteOptions : ICreatableInstance
{
	public new ExperienceInviteOptions Clone();
}

public interface ExperienceNotificationService : IServiceInstance
{
	public new ExperienceNotificationService Clone();
}

public interface ExperienceService : IServiceInstance
{
	public new ExperienceService Clone();
}

public interface ExperienceStateCaptureService : IServiceInstance
{
	public new ExperienceStateCaptureService Clone();
}

public interface ExplorerFilter : ICreatableInstance
{
	public new ExplorerFilter Clone();
}

public interface ExplorerFilterAutocompleter : Instance
{
	public new ExplorerFilterAutocompleter Clone();
}

public interface ExplorerServiceVisibilityService : IServiceInstance
{
	public new ExplorerServiceVisibilityService Clone();
}

public interface Explosion : ICreatableInstance
{
	public new Explosion Clone();
}

public interface FaceAnimatorService : IServiceInstance
{
	public new FaceAnimatorService Clone();
}

public interface FaceControls : ICreatableInstance
{
	public new FaceControls Clone();
	public float ChinRaiser { get; set; }
	public float ChinRaiserUpperLip { get; set; }
	public float Corrugator { get; set; }
	public float EyesLookDown { get; set; }
	public float EyesLookLeft { get; set; }
	public float EyesLookRight { get; set; }
	public float EyesLookUp { get; set; }
	public float FlatPucker { get; set; }
	public float Funneler { get; set; }
	public float JawDrop { get; set; }
	public float JawLeft { get; set; }
	public float JawRight { get; set; }
	public float LeftBrowLowerer { get; set; }
	public float LeftCheekPuff { get; set; }
	public float LeftCheekRaiser { get; set; }
	public float LeftDimpler { get; set; }
	public float LeftEyeClosed { get; set; }
	public float LeftEyeUpperLidRaiser { get; set; }
	public float LeftInnerBrowRaiser { get; set; }
	public float LeftLipCornerDown { get; set; }
	public float LeftLipCornerPuller { get; set; }
	public float LeftLipStretcher { get; set; }
	public float LeftLowerLipDepressor { get; set; }
	public float LeftNoseWrinkler { get; set; }
	public float LeftOuterBrowRaiser { get; set; }
	public float LeftUpperLipRaiser { get; set; }
	public float LipPresser { get; set; }
	public float LipsTogether { get; set; }
	public float LowerLipSuck { get; set; }
	public float MouthLeft { get; set; }
	public float MouthRight { get; set; }
	public float Pucker { get; set; }
	public float RightBrowLowerer { get; set; }
	public float RightCheekPuff { get; set; }
	public float RightCheekRaiser { get; set; }
	public float RightDimpler { get; set; }
	public float RightEyeClosed { get; set; }
	public float RightEyeUpperLidRaiser { get; set; }
	public float RightInnerBrowRaiser { get; set; }
	public float RightLipCornerDown { get; set; }
	public float RightLipCornerPuller { get; set; }
	public float RightLipStretcher { get; set; }
	public float RightLowerLipDepressor { get; set; }
	public float RightNoseWrinkler { get; set; }
	public float RightOuterBrowRaiser { get; set; }
	public float RightUpperLipRaiser { get; set; }
	public float TongueDown { get; set; }
	public float TongueOut { get; set; }
	public float TongueUp { get; set; }
	public float UpperLipSuck { get; set; }
}

public interface FaceInstance : Instance
{
	public new FaceInstance Clone();
}

public interface Decal : FaceInstance, ICreatableInstance;
public interface Texture : Decal, ICreatableInstance;
public interface FacialAgeEstimationService : IServiceInstance
{
	public new FacialAgeEstimationService Clone();
}

public interface FacialAnimationRecordingService : IServiceInstance
{
	public new FacialAnimationRecordingService Clone();
}

public interface FacialAnimationStreamingServiceStats : Instance
{
	public new FacialAnimationStreamingServiceStats Clone();
}

public interface FacialAnimationStreamingServiceV2 : IServiceInstance
{
	public new FacialAnimationStreamingServiceV2 Clone();
}

public interface Feature : Instance
{
	public new Feature Clone();
}

public interface FeatureRestrictionManager : IServiceInstance
{
	public new FeatureRestrictionManager Clone();
}

public interface FeedService : IServiceInstance
{
	public new FeedService Clone();
}

public interface File : Instance
{
	public new File Clone();
	public string GetBinaryContents();
	public string GetTemporaryId();
}

public interface Fire : ICreatableInstance
{
	public new Fire Clone();
}

public interface FloatCurve : ICreatableInstance
{
	public new FloatCurve Clone();
}

public interface Folder : ICreatableInstance
{
	public new Folder Clone();
}

public interface ForceField : ICreatableInstance
{
	public new ForceField Clone();
}

public interface GamePassService : IServiceInstance
{
	public new GamePassService Clone();
}

public partial interface GameSettings : Instance
{
	public new GameSettings Clone();
	public bool VideoCaptureEnabled { get; set; }
}

public interface GamepadService : IServiceInstance
{
	public new GamepadService Clone();
}

public interface GenerationService : IServiceInstance
{
	public new GenerationService Clone();
}

public interface GenericChallengeService : IServiceInstance
{
	public new GenericChallengeService Clone();
}

public interface GeometryService : IServiceInstance
{
	public new GeometryService Clone();
}

public interface GetTextBoundsParams : ICreatableInstance
{
	public new GetTextBoundsParams Clone();
}

public partial interface GlobalDataStore : Instance
{
	public new GlobalDataStore Clone();
}

public interface DataStore : GlobalDataStore;
public partial interface OrderedDataStore : GlobalDataStore;
public interface GroupService : IServiceInstance
{
	public new GroupService Clone();
}

public interface GuiBase2d : GuiBase;
public interface GuiObject : GuiBase2d;
public interface CanvasGroup : GuiObject, ICreatableInstance;
public interface Frame : GuiObject, ICreatableInstance;
public interface GuiButton : GuiObject;
public interface ImageButton : GuiButton, ICreatableInstance;
public interface TextButton : GuiButton, ICreatableInstance;
public interface ImageLabel : GuiLabel, ICreatableInstance;
public interface TextLabel : GuiLabel, ICreatableInstance;
public interface ScrollingFrame : GuiObject, ICreatableInstance;
public interface TextBox : GuiObject, ICreatableInstance;
public interface VideoDisplay : GuiObject, ICreatableInstance;
public interface VideoFrame : GuiObject, ICreatableInstance;
public interface ViewportFrame : GuiObject, ICreatableInstance;
public interface LayerCollector : GuiBase2d;
public interface BillboardGui : LayerCollector, ICreatableInstance;
public interface PluginGui : LayerCollector
{
	public string Title { get; set; }
	public void BindToClose(Action? function = null);
	public Vector2 GetRelativeMousePosition();
	public delegate void PluginDragDroppedDelegate(object dragData);
	public event PluginDragDroppedDelegate PluginDragDropped;
	public delegate void PluginDragEnteredDelegate(object dragData);
	public event PluginDragEnteredDelegate PluginDragEntered;
	public delegate void PluginDragLeftDelegate(object dragData);
	public event PluginDragLeftDelegate PluginDragLeft;
	public delegate void PluginDragMovedDelegate(object dragData);
	public event PluginDragMovedDelegate PluginDragMoved;
	public delegate void WindowFocusReleasedDelegate();
	public event WindowFocusReleasedDelegate WindowFocusReleased;
	public delegate void WindowFocusedDelegate();
	public event WindowFocusedDelegate WindowFocused;
}

public interface DockWidgetPluginGui : PluginGui;
public interface QWidgetPluginGui : PluginGui;
public interface ScreenGui : LayerCollector, ICreatableInstance;
public interface SurfaceGuiBase : LayerCollector;
public interface AdGui : SurfaceGuiBase, ICreatableInstance;
public interface SurfaceGui : SurfaceGuiBase, ICreatableInstance;
public interface GuiBase3d : GuiBase;
public interface FloorWire : GuiBase3d, ICreatableInstance;
public interface InstanceAdornment : GuiBase3d;
public interface SelectionBox : InstanceAdornment, ICreatableInstance;
public interface PVAdornment : GuiBase3d;
public interface HandleAdornment : PVAdornment;
public interface BoxHandleAdornment : HandleAdornment, ICreatableInstance;
public interface ConeHandleAdornment : HandleAdornment, ICreatableInstance;
public interface CylinderHandleAdornment : HandleAdornment, ICreatableInstance;
public interface ImageHandleAdornment : HandleAdornment, ICreatableInstance;
public interface LineHandleAdornment : HandleAdornment, ICreatableInstance;
public interface SphereHandleAdornment : HandleAdornment, ICreatableInstance;
public interface WireframeHandleAdornment : HandleAdornment, ICreatableInstance;
public interface ParabolaAdornment : PVAdornment;
public interface SelectionSphere : PVAdornment, ICreatableInstance;
public interface PartAdornment : GuiBase3d;
public interface ArcHandles : HandlesBase, ICreatableInstance;
public interface Handles : HandlesBase, ICreatableInstance;
public interface SurfaceSelection : PartAdornment, ICreatableInstance;
public interface SelectionLasso : GuiBase3d;
public interface SelectionPartLasso : SelectionLasso, ICreatableInstance;
public interface SelectionPointLasso : SelectionLasso, ICreatableInstance;
public interface Path2D : GuiBase, ICreatableInstance;
public interface GuiService : IServiceInstance
{
	public new GuiService Clone();
}

public interface HandRigDescription : ICreatableInstance
{
	public new HandRigDescription Clone();
}

public interface HapticEffect : ICreatableInstance
{
	public new HapticEffect Clone();
}

public interface HapticService : IServiceInstance
{
	public new HapticService Clone();
}

public interface HeapProfilerService : IServiceInstance
{
	public new HeapProfilerService Clone();
	public string ClientRequestDataAsync(Player player);
	public string ServerRequestDataAsync();
	public delegate void OnNewDataDelegate(Player player, Buffer jsonString, int id, int compressedLength, int uncompressedLength);
	public event OnNewDataDelegate OnNewData;
}

public interface HeightmapImporterService : IServiceInstance
{
	public new HeightmapImporterService Clone();
}

public interface HiddenSurfaceRemovalAsset : ICreatableInstance
{
	public new HiddenSurfaceRemovalAsset Clone();
}

public interface Highlight : ICreatableInstance
{
	public new Highlight Clone();
}

public interface HttpService : IServiceInstance
{
	public new HttpService Clone();
}

public interface Humanoid : ICreatableInstance
{
	public new Humanoid Clone();
}

public interface HumanoidDescription : ICreatableInstance
{
	public new HumanoidDescription Clone();
}

public interface HumanoidRigDescription : ICreatableInstance
{
	public new HumanoidRigDescription Clone();
}

public interface IKControl : ICreatableInstance
{
	public new IKControl Clone();
}

public interface IXPService : IServiceInstance
{
	public new IXPService Clone();
}

public interface ImportSession : Instance
{
	public new ImportSession Clone();
}

public interface AssetImportSession : ImportSession;
public interface IncrementalPatchBuilder : IServiceInstance
{
	public new IncrementalPatchBuilder Clone();
}

public interface InputAction : ICreatableInstance
{
	public new InputAction Clone();
}

public interface InputBinding : ICreatableInstance
{
	public new InputBinding Clone();
}

public interface InputContext : ICreatableInstance
{
	public new InputContext Clone();
}

public interface InputObject : Instance
{
	public new InputObject Clone();
}

public interface InsertService : IServiceInstance
{
	public new InsertService Clone();
}

public interface InternalSyncItem : ICreatableInstance
{
	public new InternalSyncItem Clone();
}

public interface JointInstance : Instance
{
	public new JointInstance Clone();
}

public interface DynamicRotate : JointInstance;
public interface Glue : JointInstance, ICreatableInstance;
public interface Motor : JointInstance, ICreatableInstance;
public interface Motor6D : Motor, ICreatableInstance;
public interface VelocityMotor : JointInstance, ICreatableInstance;
public interface JointsService : IServiceInstance
{
	public new JointsService Clone();
}

public interface Keyframe : ICreatableInstance
{
	public new Keyframe Clone();
}

public interface KeyframeMarker : ICreatableInstance
{
	public new KeyframeMarker Clone();
}

public partial interface KeyframeSequenceProvider : IServiceInstance
{
	public new KeyframeSequenceProvider Clone();
	public Instance GetKeyframeSequence(string assetId);
	public Instance GetKeyframeSequenceById(long assetId, bool useCache);
}

public interface LanguageService : IServiceInstance
{
	public new LanguageService Clone();
}

public interface Light : Instance
{
	public new Light Clone();
}

public interface PointLight : Light, ICreatableInstance;
public interface SpotLight : Light, ICreatableInstance;
public interface SurfaceLight : Light, ICreatableInstance;
public interface Lighting : IServiceInstance
{
	public new Lighting Clone();
}

public interface LinkingService : IServiceInstance
{
	public new LinkingService Clone();
}

public interface LiveScriptingService : IServiceInstance
{
	public new LiveScriptingService Clone();
}

public interface LiveSyncService : IServiceInstance
{
	public new LiveSyncService Clone();
}

public interface LocalizationService : IServiceInstance
{
	public new LocalizationService Clone();
}

public interface LocalizationTable : ICreatableInstance
{
	public new LocalizationTable Clone();
}

public interface LodDataEntity : Instance
{
	public new LodDataEntity Clone();
}

public interface LogReporterService : IServiceInstance
{
	public new LogReporterService Clone();
}

public interface LogService : IServiceInstance
{
	public new LogService Clone();
}

public interface LuaSettings : Instance
{
	public new LuaSettings Clone();
}

public interface LuaSourceContainer : Instance
{
	public new LuaSourceContainer Clone();
}

public interface AuroraScript : LuaSourceContainer, ICreatableInstance
{
	public bool EnableCulling { get; set; }
	public bool EnableLOD { get; set; }
	public int LODCriticality { get; set; }
	public int Priority { get; set; }
	public string Source { get; set; }
}

public interface BaseScript : LuaSourceContainer;
public interface Script : BaseScript, ICreatableInstance;
public interface ModuleScript : LuaSourceContainer, ICreatableInstance;
public interface MarkerCurve : ICreatableInstance
{
	public new MarkerCurve Clone();
}

public interface MarketplaceService : IServiceInstance
{
	public new MarketplaceService Clone();
}

public interface MatchmakingService : IServiceInstance
{
	public new MatchmakingService Clone();
}

public interface MaterialGenerationService : IServiceInstance
{
	public new MaterialGenerationService Clone();
}

public interface MaterialGenerationSession : Instance
{
	public new MaterialGenerationSession Clone();
}

public interface MaterialService : IServiceInstance
{
	public new MaterialService Clone();
}

public interface MaterialVariant : ICreatableInstance
{
	public new MaterialVariant Clone();
	public string ColorMap { get; set; }
	public Content ColorMapContent { get; set; }
	public string MetalnessMap { get; set; }
	public Content MetalnessMapContent { get; set; }
	public string NormalMap { get; set; }
	public Content NormalMapContent { get; set; }
	public string RoughnessMap { get; set; }
	public Content RoughnessMapContent { get; set; }
}

public interface MemStorageConnection : Instance
{
	public new MemStorageConnection Clone();
	public void Disconnect();
}

public interface MemoryStoreHashMap : Instance
{
	public new MemoryStoreHashMap Clone();
}

public interface MemoryStoreQueue : Instance
{
	public new MemoryStoreQueue Clone();
}

public interface MemoryStoreService : IServiceInstance
{
	public new MemoryStoreService Clone();
}

public interface MemoryStoreSortedMap : Instance
{
	public new MemoryStoreSortedMap Clone();
}

public interface MessageBusConnection : Instance
{
	public new MessageBusConnection Clone();
}

public interface MessageBusService : IServiceInstance
{
	public new MessageBusService Clone();
}

public interface MessagingService : IServiceInstance
{
	public new MessagingService Clone();
}

public interface MetaBreakpoint : Instance
{
	public new MetaBreakpoint Clone();
}

public interface MetaBreakpointContext : Instance
{
	public new MetaBreakpointContext Clone();
}

public interface MetaBreakpointManager : IServiceInstance
{
	public new MetaBreakpointManager Clone();
}

public interface Mouse : Instance
{
	public new Mouse Clone();
}

public interface PluginMouse : Mouse
{
	public delegate void DragEnterDelegate(Instance[] instances);
	public event DragEnterDelegate DragEnter;
}

public interface MultipleDocumentInterfaceInstance : Instance
{
	public new MultipleDocumentInterfaceInstance Clone();
}

public interface NetworkMarker : Instance
{
	public new NetworkMarker Clone();
}

public partial interface NetworkPeer : Instance
{
	public new NetworkPeer Clone();
	public void SetOutgoingKBPSLimit(int limit);
}

public partial interface NetworkClient : NetworkPeer, IServiceInstance;
public partial interface NetworkServer : NetworkPeer, IServiceInstance;
public interface NetworkReplicator : Instance
{
	public new NetworkReplicator Clone();
	public Instance GetPlayer();
}

public interface ClientReplicator : NetworkReplicator;
public interface ServerReplicator : NetworkReplicator;
public interface NetworkSettings : IServiceInstance
{
	public new NetworkSettings Clone();
	public bool HttpProxyEnabled { get; }
	public string HttpProxyURL { get; }
	public float IncomingReplicationLag { get; set; }
	public bool PrintJoinSizeBreakdown { get; set; }
	public bool PrintPhysicsErrors { get; set; }
	public bool PrintStreamInstanceQuota { get; set; }
	public bool RandomizeJoinInstanceOrder { get; set; }
	public bool RenderStreamedRegions { get; set; }
	public bool ShowActiveAnimationAsset { get; set; }
}

public interface NoCollisionConstraint : ICreatableInstance
{
	public new NoCollisionConstraint Clone();
}

public interface Noise : ICreatableInstance
{
	public new Noise Clone();
}

public interface OmniRecommendationsService : IServiceInstance
{
	public new OmniRecommendationsService Clone();
}

public interface OpenCloudApiV1 : Instance
{
	public new OpenCloudApiV1 Clone();
}

public interface OpenCloudService : IServiceInstance
{
	public new OpenCloudService Clone();
}

public interface PVInstance : Instance
{
	public new PVInstance Clone();
}

public partial interface BasePart : PVInstance;
public interface FormFactorPart : BasePart;
public interface Part : FormFactorPart, ICreatableInstance;
public interface Platform : Part;
public interface Seat : Part, ICreatableInstance;
public interface SkateboardPlatform : Part, ICreatableInstance;
public interface SpawnLocation : Part, ICreatableInstance;
public partial interface Terrain : BasePart
{
	public void ConvertToSmooth();
}

public interface TriangleMeshPart : BasePart;
public interface MeshPart : TriangleMeshPart, ICreatableInstance;
public interface PartOperation : TriangleMeshPart, ICreatableInstance;
public interface NegateOperation : PartOperation, ICreatableInstance;
public interface TrussPart : BasePart, ICreatableInstance;
public interface VehicleSeat : BasePart, ICreatableInstance;
public interface Camera : PVInstance, ICreatableInstance;
public interface Model : PVInstance, ICreatableInstance
{
	public Enum.ModelLevelOfDetail LevelOfDetail { get; set; }
}

public interface Actor : Model, ICreatableInstance;
public interface BackpackItem : Model;
public interface Tool : BackpackItem, ICreatableInstance;
public partial interface WorldRoot : Model
{
	public void IKMoveTo(BasePart part, CFrame target, float? translateStiffness = null, float? rotateStiffness = null, Enum.IKCollisionsMode? collisionsMode = null);
	public void StepPhysics(float dt, Instance[]? parts = null);
}

public partial interface Workspace : WorldRoot, IServiceInstance
{
	public void BreakJoints(Instance[] objects);
	public void MakeJoints(Instance[] objects);
	public void ZoomToExtents();
}

public interface PackageLink : Instance
{
	public new PackageLink Clone();
}

public interface PackageService : IServiceInstance
{
	public new PackageService Clone();
}

public interface PackageUIService : IServiceInstance
{
	public new PackageUIService Clone();
}

public interface Pages : Instance
{
	public new Pages Clone();
}

public interface DataStoreKeyPages : Pages;
public interface DataStoreListingPages : Pages;
public interface ParticleEmitter : ICreatableInstance
{
	public new ParticleEmitter Clone();
}

public interface PatchMapping : Instance
{
	public new PatchMapping Clone();
}

public interface Path : Instance
{
	public new Path Clone();
}

public interface PathfindingLink : ICreatableInstance
{
	public new PathfindingLink Clone();
}

public interface PathfindingModifier : ICreatableInstance
{
	public new PathfindingModifier Clone();
}

public interface PathfindingService : IServiceInstance
{
	public new PathfindingService Clone();
}

public interface PausedState : Instance
{
	public new PausedState Clone();
}

public interface PausedStateBreakpoint : PausedState;
public interface PausedStateException : PausedState;
public interface PerformanceControlService : IServiceInstance
{
	public new PerformanceControlService Clone();
}

public interface PhysicsService : IServiceInstance
{
	public new PhysicsService Clone();
}

public interface PhysicsSettings : Instance
{
	public new PhysicsSettings Clone();
	public bool AllowSleep { get; set; }
	public bool AreAnchorsShown { get; set; }
	public bool AreAssembliesShown { get; set; }
	public bool AreAwakePartsHighlighted { get; set; }
	public bool AreBodyTypesShown { get; set; }
	public bool AreContactIslandsShown { get; set; }
	public bool AreContactPointsShown { get; set; }
	public bool AreJointCoordinatesShown { get; set; }
	public bool AreMechanismsShown { get; set; }
	public bool AreModelCoordsShown { get; set; }
	public bool AreNonAnchorsShown { get; set; }
	public bool AreOwnersShown { get; set; }
	public bool ArePartCoordsShown { get; set; }
	public bool AreRegionsShown { get; set; }
	public bool AreTerrainReplicationRegionsShown { get; set; }
	public bool AreUnalignedPartsShown { get; set; }
	public bool AreWorldCoordsShown { get; set; }
	public bool DisableCSGv2 { get; set; }
	public bool DisableCSGv3ForPlugins { get; set; }
	public bool IsInterpolationThrottleShown { get; set; }
	public bool IsReceiveAgeShown { get; set; }
	public bool IsTreeShown { get; set; }
	public Enum.EnviromentalPhysicsThrottle PhysicsEnvironmentalThrottle { get; set; }
	public bool ShowDecompositionGeometry { get; set; }
	public float ThrottleAdjustTime { get; set; }
	public bool UseCSGv2 { get; set; }
}

public interface PlacesService : IServiceInstance
{
	public new PlacesService Clone();
}

public interface PlatformCloudStorageService : IServiceInstance
{
	public new PlatformCloudStorageService Clone();
}

public interface PlatformFriendsService : IServiceInstance
{
	public new PlatformFriendsService Clone();
}

public partial interface Player : Instance
{
	public new Player Clone();
	public void SetAccountAge(int accountAge);
	public void SetSuperSafeChat(bool value);
}

public interface PlayerData : Instance
{
	public new PlayerData Clone();
}

public interface PlayerDataRecord : Instance
{
	public new PlayerDataRecord Clone();
}

public interface PlayerDataRecordConfig : Instance
{
	public new PlayerDataRecordConfig Clone();
}

public interface PlayerDataService : IServiceInstance
{
	public new PlayerDataService Clone();
}

public interface PlayerHydrationService : IServiceInstance
{
	public new PlayerHydrationService Clone();
}

public partial interface PlayerScripts : Instance
{
	public new PlayerScripts Clone();
}

public interface PlayerViewService : IServiceInstance
{
	public new PlayerViewService Clone();
}

public partial interface Players : IServiceInstance
{
	public new Players Clone();
	public void Chat(string message);
	public void SetChatStyle(Enum.ChatStyle? style = null);
	public void TeamChat(string message);
}

public interface Plugin : Instance
{
	public new Plugin Clone();
	public bool CollisionEnabled { get; }
	public float GridSize { get; }
	public void Activate(bool exclusiveMouse);
	public PluginAction CreatePluginAction(string actionId, string text, string statusTip, string iconName, bool? allowBinding = null);
	public PluginMenu CreatePluginMenu(string id, string title, string icon);
	public PluginToolbar CreateToolbar(string name);
	public void Deactivate();
	public Enum.JointCreationMode GetJoinMode();
	public PluginMouse GetMouse();
	public Enum.RibbonTool GetSelectedRibbonTool();
	public object GetSetting(string key);
	public long GetStudioUserId();
	public Instance Intersect(Instance[] objects);
	public bool IsActivated();
	public bool IsActivatedWithExclusiveMouse();
	public Instance[] Negate(Instance[] objects);
	public void OpenScript(LuaSourceContainer script, int? lineNumber = null);
	public void OpenWikiPage(string url);
	public void SaveSelectedToRoblox();
	public void SelectRibbonTool(Enum.RibbonTool tool, UDim2 position);
	public Instance[] Separate(Instance[] objects);
	public void SetSetting(string key, object value);
	public void StartDrag(object dragData);
	public Instance Union(Instance[] objects);
	public DockWidgetPluginGui CreateDockWidgetPluginGui(string pluginGuiId, DockWidgetPluginGuiInfo dockWidgetPluginGuiInfo);
	public Instance ImportFbxAnimation(object rigModel, bool? isR15 = null);
	public Instance ImportFbxRig(bool? isR15 = null);
	public long PromptForExistingAssetId(string assetType);
	public bool PromptSaveSelection(string suggestedFileName);
	public delegate void DeactivationDelegate();
	public event DeactivationDelegate Deactivation;
	public delegate void UnloadingDelegate();
	public event UnloadingDelegate Unloading;
}

public interface PluginAction : ICreatableInstance
{
	public new PluginAction Clone();
	public string ActionId { get; }
	public bool AllowBinding { get; }
	public string StatusTip { get; }
	public string Text { get; }
	public delegate void TriggeredDelegate();
	public event TriggeredDelegate Triggered;
}

public interface PluginCapabilities : ICreatableInstance
{
	public new PluginCapabilities Clone();
}

public interface PluginDebugService : IServiceInstance
{
	public new PluginDebugService Clone();
}

public interface PluginDragEvent : Instance
{
	public new PluginDragEvent Clone();
	public string Data { get; }
	public string MimeType { get; }
	public Vector2 Position { get; }
	public string Sender { get; }
}

public interface PluginGuiService : IServiceInstance
{
	public new PluginGuiService Clone();
}

public interface PluginManagementService : IServiceInstance
{
	public new PluginManagementService Clone();
}

public partial interface PluginManagerInterface : Instance
{
	public new PluginManagerInterface Clone();
	public Instance CreatePlugin();
	public void ExportPlace(string filePath);
	public void ExportSelection(string filePath);
}

public interface PluginMenu : Instance
{
	public new PluginMenu Clone();
	public string Icon { get; set; }
	public string Title { get; set; }
	public void AddAction(Instance action);
	public void AddMenu(Instance menu);
	public Instance AddNewAction(string actionId, string text, string icon);
	public void AddSeparator();
	public void Clear();
	public Instance ShowAsync();
}

public interface PluginPolicyService : IServiceInstance
{
	public new PluginPolicyService Clone();
}

public interface PluginToolbar : Instance
{
	public new PluginToolbar Clone();
	public PluginToolbarButton CreateButton(string buttonId, string tooltip, string iconname, string text);
}

public interface PluginToolbarButton : Instance
{
	public new PluginToolbarButton Clone();
	public bool ClickableWhenViewportHidden { get; set; }
	public bool Enabled { get; set; }
	public string Icon { get; set; }
	public void SetActive(bool active);
	public delegate void ClickDelegate();
	public event ClickDelegate Click;
}

public interface PolicyService : IServiceInstance
{
	public new PolicyService Clone();
}

public interface PoseBase : Instance
{
	public new PoseBase Clone();
}

public interface NumberPose : PoseBase, ICreatableInstance;
public interface Pose : PoseBase, ICreatableInstance;
public interface PostEffect : Instance
{
	public new PostEffect Clone();
}

public interface BloomEffect : PostEffect, ICreatableInstance;
public interface BlurEffect : PostEffect, ICreatableInstance;
public interface ColorCorrectionEffect : PostEffect, ICreatableInstance;
public interface ColorGradingEffect : PostEffect, ICreatableInstance;
public interface DepthOfFieldEffect : PostEffect, ICreatableInstance;
public interface SunRaysEffect : PostEffect, ICreatableInstance;
public interface ProximityPrompt : ICreatableInstance
{
	public new ProximityPrompt Clone();
}

public interface ProximityPromptService : IServiceInstance
{
	public new ProximityPromptService Clone();
}

public interface PublishService : IServiceInstance
{
	public new PublishService Clone();
}

public interface RTAnimationTracker : ICreatableInstance
{
	public new RTAnimationTracker Clone();
}

public interface ReflectionService : IServiceInstance
{
	public new ReflectionService Clone();
}

public interface RemoteCursorService : IServiceInstance
{
	public new RemoteCursorService Clone();
}

public interface RenderSettings : IServiceInstance
{
	public new RenderSettings Clone();
	public int AutoFRMLevel { get; set; }
	public bool EagerBulkExecution { get; set; }
	public Enum.QualityLevel EditQualityLevel { get; set; }
	public bool EnableVRMode { get; set; }
	public bool ExportMergeByMaterial { get; set; }
	public Enum.FramerateManagerMode FrameRateManager { get; set; }
	public Enum.GraphicsMode GraphicsMode { get; set; }
	public int MeshCacheSize { get; set; }
	public Enum.MeshPartDetailLevel MeshPartDetailLevel { get; set; }
	public Enum.QualityLevel QualityLevel { get; set; }
	public bool ReloadAssets { get; set; }
	public bool RenderCSGTrianglesDebug { get; set; }
	public bool ShowBoundingBoxes { get; set; }
	public Enum.ViewMode ViewMode { get; set; }
	public int GetMaxQualityLevel();
}

public interface RenderingTest : ICreatableInstance
{
	public new RenderingTest Clone();
	public CFrame CFrame { get; set; }
	public int ComparisonDiffThreshold { get; set; }
	public Enum.RenderingTestComparisonMethod ComparisonMethod { get; set; }
	public float ComparisonPsnrThreshold { get; set; }
	public string Description { get; set; }
	public float FieldOfView { get; set; }
	public bool PerfTest { get; set; }
	public bool QualityAuto { get; set; }
	public int QualityLevel { get; set; }
	public int RenderingTestFrameCount { get; set; }
	public bool ShouldSkip { get; set; }
	public string Ticket { get; set; }
	public int Timeout { get; set; }
	public void RenderdocTriggerCapture();
}

public partial interface ReplicatedFirst : IServiceInstance
{
	public new ReplicatedFirst Clone();
}

public interface RibbonNotificationService : IServiceInstance
{
	public new RibbonNotificationService Clone();
}

public interface RobloxPluginGuiService : IServiceInstance
{
	public new RobloxPluginGuiService Clone();
}

public interface RobloxSerializableInstance : Instance
{
	public new RobloxSerializableInstance Clone();
}

public interface RomarkService : IServiceInstance
{
	public new RomarkService Clone();
}

public interface RotationCurve : ICreatableInstance
{
	public new RotationCurve Clone();
}

public partial interface RunService : IServiceInstance
{
	public new RunService Clone();
	public Enum.RunState RunState { get; set; }
	public bool IsEdit();
	public void Pause();
	public void Reset();
	public void Run();
	public void Stop();
}

public interface SafetyService : IServiceInstance
{
	public new SafetyService Clone();
}

public interface ScreenshotHud : Instance
{
	public new ScreenshotHud Clone();
}

public interface SyncScriptBuilder : ScriptBuilder;
public interface ScriptChangeService : IServiceInstance
{
	public new ScriptChangeService Clone();
}

public partial interface ScriptContext : IServiceInstance
{
	public new ScriptContext Clone();
	public void SetTimeout(float seconds);
}

public interface ScriptDebugger : Instance
{
	public new ScriptDebugger Clone();
	public int CurrentLine { get; }
	public bool IsDebugging { get; }
	public bool IsPaused { get; }
	public Instance? Script { get; }
	public Instance AddWatch(string expression);
	public Instance[] GetBreakpoints();
	public object GetGlobals(int? stackFrame = null);
	public object GetLocals(int? stackFrame = null);
	public object[] GetStack();
	public object GetUpvalues(int? stackFrame = null);
	public object GetWatchValue(Instance watch);
	public Instance[] GetWatches();
	public Instance SetBreakpoint(int line, bool isContextDependentBreakpoint);
	public void SetGlobal(string name, object value, int stackFrame);
	public void SetLocal(string name, object value, int? stackFrame = null);
	public void SetUpvalue(string name, object value, int? stackFrame = null);
	public delegate void BreakpointAddedDelegate(Instance breakpoint);
	public event BreakpointAddedDelegate BreakpointAdded;
	public delegate void BreakpointRemovedDelegate(Instance breakpoint);
	public event BreakpointRemovedDelegate BreakpointRemoved;
	public delegate void EncounteredBreakDelegate(int line, Enum.BreakReason breakReason);
	public event EncounteredBreakDelegate EncounteredBreak;
	public delegate void ResumingDelegate();
	public event ResumingDelegate Resuming;
	public delegate void WatchAddedDelegate(Instance watch);
	public event WatchAddedDelegate WatchAdded;
	public delegate void WatchRemovedDelegate(Instance watch);
	public event WatchRemovedDelegate WatchRemoved;
}

public partial interface ScriptDocument : Instance
{
	public new ScriptDocument Clone();
	public string GetLine(int? lineIndex = null);
	public int GetLineCount();
	public LuaSourceContainer GetScript();
	public string GetSelectedText();
	public object GetSelection();
	public object GetSelectionEnd();
	public object GetSelectionStart();
	public string GetText(int? startLine = null, int? startCharacter = null, int? endLine = null, int? endCharacter = null);
	public object GetViewport();
	public bool HasSelectedText();
	public bool IsCommandBar();
	public object CloseAsync();
	public object EditTextAsync(string newText, int startLine, int startCharacter, int endLine, int endCharacter);
	public object ForceSetSelectionAsync(int cursorLine, int cursorCharacter, int? anchorLine = null, int? anchorCharacter = null);
	public object MultiEditTextAsync(object[] edits);
	public object RequestSetSelectionAsync(int cursorLine, int cursorCharacter, int? anchorLine = null, int? anchorCharacter = null);
	public delegate void SelectionChangedDelegate(long positionLine, long positionCharacter, long anchorLine, long anchorCharacter);
	public event SelectionChangedDelegate SelectionChanged;
	public delegate void ViewportChangedDelegate(long startLine, long endLine);
	public event ViewportChangedDelegate ViewportChanged;
}

public partial interface ScriptEditorService : IServiceInstance
{
	public new ScriptEditorService Clone();
	public void DeregisterAutocompleteCallback(string name);
	public void DeregisterScriptAnalysisCallback(string name);
	public ScriptDocument FindScriptDocument(LuaSourceContainer script);
	public string GetEditorSource(LuaSourceContainer script);
	public Instance[] GetScriptDocuments();
	public void RegisterAutocompleteCallback(string name, int priority, Action callbackFunction);
	public void RegisterScriptAnalysisCallback(string name, int priority, Action callbackFunction);
	public object OpenScriptDocumentAsync(LuaSourceContainer script);
	public void UpdateSourceAsync(LuaSourceContainer script, Action callback);
	public delegate void TextDocumentDidChangeDelegate(ScriptDocument document, object changesArray);
	public event TextDocumentDidChangeDelegate TextDocumentDidChange;
	public delegate void TextDocumentDidCloseDelegate(ScriptDocument oldDocument);
	public event TextDocumentDidCloseDelegate TextDocumentDidClose;
	public delegate void TextDocumentDidOpenDelegate(ScriptDocument newDocument);
	public event TextDocumentDidOpenDelegate TextDocumentDidOpen;
}

public partial interface ScriptProfilerService : IServiceInstance
{
	public new ScriptProfilerService Clone();
	public void ClientRequestData(Player player);
	public void ClientStart(Player player, int? frequency = null);
	public void ClientStop(Player player);
	public object DeserializeJSON(string? jsonString = null);
	public void ServerRequestData();
	public void ServerStart(int? frequency = null);
	public void ServerStop();
	public delegate void OnNewDataDelegate(Player player, string jsonString);
	public event OnNewDataDelegate OnNewData;
}

public interface ScriptRegistrationService : IServiceInstance
{
	public new ScriptRegistrationService Clone();
}

public interface Selection : IServiceInstance
{
	public new Selection Clone();
	public float SelectionThickness { get; }
	public void Add(Instance[] instancesToAdd);
	public Instance[] Get();
	public void Remove(Instance[] instancesToRemove);
	public void Set(Instance[] selection);
	public delegate void SelectionChangedDelegate();
	public event SelectionChangedDelegate SelectionChanged;
}

public interface SensorBase : Instance
{
	public new SensorBase Clone();
}

public interface AtmosphereSensor : SensorBase, ICreatableInstance;
public interface BuoyancySensor : SensorBase, ICreatableInstance;
public interface ControllerPartSensor : ControllerSensor, ICreatableInstance;
public interface FluidForceSensor : SensorBase, ICreatableInstance;
public interface SerializationService : IServiceInstance
{
	public new SerializationService Clone();
}

public partial interface ServerScriptService : IServiceInstance
{
	public new ServerScriptService Clone();
}

public partial interface ServiceProvider : Instance
{
	public new ServiceProvider Clone();
}

public partial interface DataModel : ServiceProvider
{
	public object[] GetJobsInfo();
	public Instance[] GetObjects(string url);
	public void SetPlaceId(long placeId);
	public void SetUniverseId(long universeId);
}

public interface GlobalSettings : GenericSettings
{
	public bool GetFFlag(string name);
	public string GetFVariable(string name);
}

public interface UserSettings : GenericSettings;
public interface ServiceVisibilityService : IServiceInstance
{
	public new ServiceVisibilityService Clone();
}

public interface SessionService : IServiceInstance
{
	public new SessionService Clone();
}

public interface SharedTableRegistry : IServiceInstance
{
	public new SharedTableRegistry Clone();
}

public interface Sky : ICreatableInstance
{
	public new Sky Clone();
}

public interface Smoke : ICreatableInstance
{
	public new Smoke Clone();
}

public interface SmoothVoxelsUpgraderService : IServiceInstance
{
	public new SmoothVoxelsUpgraderService Clone();
}

public interface SocialService : IServiceInstance
{
	public new SocialService Clone();
}

public interface Sound : ICreatableInstance
{
	public new Sound Clone();
}

public interface SoundEffect : Instance
{
	public new SoundEffect Clone();
}

public interface ChorusSoundEffect : SoundEffect, ICreatableInstance;
public interface CompressorSoundEffect : SoundEffect, ICreatableInstance;
public interface ChannelSelectorSoundEffect : CustomSoundEffect;
public interface DistortionSoundEffect : SoundEffect, ICreatableInstance;
public interface EchoSoundEffect : SoundEffect, ICreatableInstance;
public interface EqualizerSoundEffect : SoundEffect, ICreatableInstance;
public interface FlangeSoundEffect : SoundEffect, ICreatableInstance;
public interface PitchShiftSoundEffect : SoundEffect, ICreatableInstance;
public interface ReverbSoundEffect : SoundEffect, ICreatableInstance;
public interface TremoloSoundEffect : SoundEffect, ICreatableInstance;
public interface SoundGroup : ICreatableInstance
{
	public new SoundGroup Clone();
}

public partial interface SoundService : IServiceInstance
{
	public new SoundService Clone();
	public Enum.ListenerLocation DefaultListenerLocation { get; set; }
	public void OpenAttenuationCurveEditor(Instance[] selectedCurveObjects);
	public void OpenDirectionalCurveEditor(Instance[] selectedCurveObjects);
}

public interface Sparkles : ICreatableInstance
{
	public new Sparkles Clone();
}

public interface StackFrame : Instance
{
	public new StackFrame Clone();
}

public interface StartPageService : IServiceInstance
{
	public new StartPageService Clone();
}

public interface StarterPlayer : IServiceInstance
{
	public new StarterPlayer Clone();
}

public interface StartupMessageService : IServiceInstance
{
	public new StartupMessageService Clone();
}

public interface Stats : IServiceInstance
{
	public new Stats Clone();
}

public interface StatsItem : Instance
{
	public new StatsItem Clone();
	public float GetValue();
	public string GetValueString();
}

public interface RunningAverageItemDouble : StatsItem;
public interface RunningAverageItemInt : StatsItem;
public interface RunningAverageTimeIntervalItem : StatsItem;
public interface TotalCountTimeIntervalItem : StatsItem;
public interface StreamingService : IServiceInstance
{
	public new StreamingService Clone();
}

public interface StudioAssetService : IServiceInstance
{
	public new StudioAssetService Clone();
}

public interface StudioAttachment : ICreatableInstance
{
	public new StudioAttachment Clone();
}

public interface StudioCallout : ICreatableInstance
{
	public new StudioCallout Clone();
}

public interface StudioCameraService : IServiceInstance
{
	public new StudioCameraService Clone();
}

public interface StudioData : IServiceInstance
{
	public new StudioData Clone();
}

public interface StudioDeviceEmulatorService : IServiceInstance
{
	public new StudioDeviceEmulatorService Clone();
}

public interface StudioWidget : StudioObjectBase;
public interface StudioPublishService : IServiceInstance
{
	public new StudioPublishService Clone();
}

public interface StudioSdkService : IServiceInstance
{
	public new StudioSdkService Clone();
}

public interface StudioService : IServiceInstance
{
	public new StudioService Clone();
	public Instance? ActiveScript { get; }
	public bool DraggerSolveConstraints { get; }
	public bool DrawConstraintsOnTop { get; }
	public float GridSize { get; }
	public float RotateIncrement { get; }
	public bool ShowConstraintDetails { get; }
	public string StudioLocaleId { get; }
	public bool UseLocalSpace { get; set; }
	public object GetClassIcon(string className);
	public long GetUserId();
	public RaycastResult? GizmoRaycast(Vector3 origin, Vector3 direction, RaycastParams? raycastParams = null);
	public Instance PromptImportFile(object[]? fileTypeFilter = null);
	public Instance[] PromptImportFiles(object[]? fileTypeFilter = null);
}

public interface StudioTheme : Instance
{
	public new StudioTheme Clone();
	public Color3 GetColor(Enum.StudioStyleGuideColor styleguideitem, Enum.StudioStyleGuideModifier? modifier = null);
}

public interface StudioUserService : IServiceInstance
{
	public new StudioUserService Clone();
}

public interface StudioWidgetsService : IServiceInstance
{
	public new StudioWidgetsService Clone();
}

public interface StyleBase : Instance
{
	public new StyleBase Clone();
}

public interface StyleRule : StyleBase, ICreatableInstance;
public interface StyleSheet : StyleBase, ICreatableInstance;
public interface StyleDerive : ICreatableInstance
{
	public new StyleDerive Clone();
}

public interface StyleLink : ICreatableInstance
{
	public new StyleLink Clone();
}

public interface StylingService : IServiceInstance
{
	public new StylingService Clone();
}

public interface SurfaceAppearance : ICreatableInstance
{
	public new SurfaceAppearance Clone();
	public Enum.AlphaMode AlphaMode { get; set; }
	public string ColorMap { get; set; }
	public string MetalnessMap { get; set; }
	public string NormalMap { get; set; }
	public string RoughnessMap { get; set; }
}

public interface SystemThemeService : IServiceInstance
{
	public new SystemThemeService Clone();
}

public interface TaskScheduler : IServiceInstance
{
	public new TaskScheduler Clone();
	public float SchedulerDutyCycle { get; }
	public float SchedulerRate { get; }
	public Enum.ThreadPoolConfig ThreadPoolConfig { get; set; }
	public int ThreadPoolSize { get; }
}

public interface Team : ICreatableInstance
{
	public new Team Clone();
}

public interface TeamCreateData : IServiceInstance
{
	public new TeamCreateData Clone();
}

public interface TeamCreatePublishService : IServiceInstance
{
	public new TeamCreatePublishService Clone();
}

public interface TeamCreateService : IServiceInstance
{
	public new TeamCreateService Clone();
}

public interface Teams : IServiceInstance
{
	public new Teams Clone();
}

public interface TelemetryService : IServiceInstance
{
	public new TelemetryService Clone();
}

public interface TeleportAsyncResult : Instance
{
	public new TeleportAsyncResult Clone();
}

public interface TeleportOptions : ICreatableInstance
{
	public new TeleportOptions Clone();
}

public interface TeleportService : IServiceInstance
{
	public new TeleportService Clone();
}

public interface TerrainDetail : ICreatableInstance
{
	public new TerrainDetail Clone();
	public string ColorMap { get; set; }
	public Content ColorMapContent { get; set; }
	public string MetalnessMap { get; set; }
	public Content MetalnessMapContent { get; set; }
	public string NormalMap { get; set; }
	public Content NormalMapContent { get; set; }
	public string RoughnessMap { get; set; }
	public Content RoughnessMapContent { get; set; }
}

public partial interface TerrainRegion : ICreatableInstance
{
	public new TerrainRegion Clone();
	public void ConvertToSmooth();
}

public interface TestService : IServiceInstance
{
	public new TestService Clone();
	public bool AutoRuns { get; set; }
	public string Description { get; set; }
	public int ErrorCount { get; }
	public bool ExecuteWithStudioRun { get; set; }
	public bool Is30FpsThrottleEnabled { get; set; }
	public bool IsPhysicsEnvironmentalThrottled { get; set; }
	public bool IsSleepAllowed { get; set; }
	public int NumberOfPlayers { get; set; }
	public float SimulateSecondsLag { get; set; }
	public int TestCount { get; }
	public bool ThrottlePhysicsToRealtime { get; set; }
	public float Timeout { get; set; }
	public int WarnCount { get; }
	public void Check(bool condition, string description, Instance? source = null, int? line = null);
	public void Checkpoint(string text, Instance? source = null, int? line = null);
	public void Done();
	public void Error(string description, Instance? source = null, int? line = null);
	public void Fail(string description, Instance? source = null, int? line = null);
	public void Message(string text, Instance? source = null, int? line = null);
	public void Require(bool condition, string description, Instance? source = null, int? line = null);
	public object ScopeTime();
	public void Warn(bool condition, string description, Instance? source = null, int? line = null);
	public bool isFeatureEnabled(string name);
	public void Run();
	public delegate void ServerCollectConditionalResultDelegate(bool condition, string text, Instance script, int line);
	public event ServerCollectConditionalResultDelegate ServerCollectConditionalResult;
	public delegate void ServerCollectResultDelegate(string text, Instance script, int line);
	public event ServerCollectResultDelegate ServerCollectResult;
}

public interface TextChannel : ICreatableInstance
{
	public new TextChannel Clone();
}

public interface TextChatCommand : ICreatableInstance
{
	public new TextChatCommand Clone();
}

public interface BubbleChatConfiguration : TextChatConfigurations;
public interface ChannelTabsConfiguration : TextChatConfigurations;
public interface ChatInputBarConfiguration : TextChatConfigurations;
public interface ChatWindowConfiguration : TextChatConfigurations;
public interface TextChatMessage : Instance
{
	public new TextChatMessage Clone();
}

public interface TextChatMessageProperties : ICreatableInstance
{
	public new TextChatMessageProperties Clone();
}

public interface BubbleChatMessageProperties : TextChatMessageProperties, ICreatableInstance;
public interface ChatWindowMessageProperties : TextChatMessageProperties;
public interface TextChatService : IServiceInstance
{
	public new TextChatService Clone();
}

public interface TextFilterResult : Instance
{
	public new TextFilterResult Clone();
}

public interface TextFilterTranslatedResult : Instance
{
	public new TextFilterTranslatedResult Clone();
}

public interface TextService : IServiceInstance
{
	public new TextService Clone();
}

public interface TextSource : Instance
{
	public new TextSource Clone();
}

public interface TextureGenerationPartGroup : Instance
{
	public new TextureGenerationPartGroup Clone();
}

public interface TextureGenerationService : IServiceInstance
{
	public new TextureGenerationService Clone();
}

public interface TextureGenerationUnwrappingRequest : Instance
{
	public new TextureGenerationUnwrappingRequest Clone();
}

public interface ThreadState : Instance
{
	public new ThreadState Clone();
}

public interface ToastNotificationService : IServiceInstance
{
	public new ToastNotificationService Clone();
}

public interface TracerService : IServiceInstance
{
	public new TracerService Clone();
}

public interface TrackerLodController : Instance
{
	public new TrackerLodController Clone();
}

public interface Trail : ICreatableInstance
{
	public new Trail Clone();
}

public interface Translator : Instance
{
	public new Translator Clone();
}

public interface TutorialService : IServiceInstance
{
	public new TutorialService Clone();
}

public interface TweenBase : Instance
{
	public new TweenBase Clone();
}

public interface Tween : TweenBase;
public interface TweenService : IServiceInstance
{
	public new TweenService Clone();
}

public interface UIAspectRatioConstraint : UIConstraint, ICreatableInstance;
public interface UISizeConstraint : UIConstraint, ICreatableInstance;
public interface UITextSizeConstraint : UIConstraint, ICreatableInstance;
public interface UICorner : UIComponent, ICreatableInstance;
public interface UIDragDetector : UIComponent, ICreatableInstance;
public interface UIFlexItem : UIComponent, ICreatableInstance;
public interface UIGradient : UIComponent, ICreatableInstance;
public interface UIGridStyleLayout : UILayout;
public interface UIGridLayout : UIGridStyleLayout, ICreatableInstance;
public interface UIListLayout : UIGridStyleLayout, ICreatableInstance;
public interface UIPageLayout : UIGridStyleLayout, ICreatableInstance;
public interface UITableLayout : UIGridStyleLayout, ICreatableInstance;
public interface UIPadding : UIComponent, ICreatableInstance;
public interface UIScale : UIComponent, ICreatableInstance;
public interface UIStroke : UIComponent, ICreatableInstance;
public interface UniqueIdLookupService : IServiceInstance
{
	public new UniqueIdLookupService Clone();
}

public interface UnvalidatedAssetService : IServiceInstance
{
	public new UnvalidatedAssetService Clone();
}

public interface UserGameSettings : Instance
{
	public new UserGameSettings Clone();
}

public interface UserInputService : IServiceInstance
{
	public new UserInputService Clone();
}

public interface UserService : IServiceInstance
{
	public new UserService Clone();
}

public interface VRService : IServiceInstance
{
	public new VRService Clone();
}

public interface BoolValue : ValueBase, ICreatableInstance;
public interface BrickColorValue : ValueBase, ICreatableInstance;
public interface CFrameValue : ValueBase, ICreatableInstance;
public interface Color3Value : ValueBase, ICreatableInstance;
public interface DoubleConstrainedValue : ValueBase, ICreatableInstance;
public interface IntConstrainedValue : ValueBase, ICreatableInstance;
public interface IntValue : ValueBase, ICreatableInstance;
public interface NumberValue : ValueBase, ICreatableInstance;
public interface ObjectValue : ValueBase, ICreatableInstance;
public interface RayValue : ValueBase, ICreatableInstance;
public interface StringValue : ValueBase, ICreatableInstance;
public interface Vector3Value : ValueBase, ICreatableInstance;
public interface Vector3Curve : ICreatableInstance
{
	public new Vector3Curve Clone();
}

public interface VersionControlService : IServiceInstance
{
	public new VersionControlService Clone();
}

public interface VideoCaptureService : IServiceInstance
{
	public new VideoCaptureService Clone();
}

public interface VideoDeviceInput : ICreatableInstance
{
	public new VideoDeviceInput Clone();
}

public interface VideoPlayer : ICreatableInstance
{
	public new VideoPlayer Clone();
}

public interface VisualizationMode : ICreatableInstance
{
	public new VisualizationMode Clone();
}

public interface VisualizationModeCategory : ICreatableInstance
{
	public new VisualizationModeCategory Clone();
}

public interface VoiceChatInternal : IServiceInstance
{
	public new VoiceChatInternal Clone();
}

public interface VoiceChatService : IServiceInstance
{
	public new VoiceChatService Clone();
	public Enum.VoiceChatDistanceAttenuationType DefaultDistanceAttenuation { get; set; }
	public bool EnableDefaultVoice { get; set; }
	public Enum.AudioApiRollout UseAudioApi { get; set; }
}

public interface WebSocketClient : Instance
{
	public new WebSocketClient Clone();
}

public interface WebSocketService : IServiceInstance
{
	public new WebSocketService Clone();
}

public interface WebViewService : IServiceInstance
{
	public new WebViewService Clone();
}

public interface WeldConstraint : ICreatableInstance
{
	public new WeldConstraint Clone();
}

public interface Wire : ICreatableInstance
{
	public new Wire Clone();
}

public interface TerrainIterateOperation : Object;
public interface TerrainModifyOperation : Object;
public interface TerrainReadOperation : Object;
public interface TerrainWriteOperation : Object;
