namespace TypeGenerator.Generators
{
    internal sealed class EnumGenerator(string filePath, ReflectionMetadataReader reflectionMetadata)
        : Generator(filePath, reflectionMetadata)
    {
        public void Generate(APITypes.Enum[] rbxEnums)
        {
            Write("// THIS FILE IS AUTOMATICALLY GENERATED AND SHOULD NOT BE EDITED MANUALLY!");
            Write("// GENERATED ROBLOX ENUMS");
            Write();

            Write("namespace Roblox.Enum");
            Write("{");
            PushIndent();
            foreach (var rbxEnum in rbxEnums)
            {
                var enumTypeName = rbxEnum.Name;
                var enumItems = rbxEnum.Items;
                Write($"public static class {enumTypeName}");
                Write("{");
                PushIndent();
                Write("public interface Type : EnumItem");
                Write("{");
                Write("}");
                Write();

                var blacklistedItems = Constants.ENUM_BLACKLIST.GetValueOrDefault(rbxEnum.Name) ?? [];
                foreach (var item in enumItems)
                {
                    if (blacklistedItems.Contains(item.Name)) continue;
                    Write($"public static extern Type {item.Name} {{ get; }}");
                }
                
                Write();
                Write("/// <summary>Returns an array of all <see cref=\"EnumItem\"/> options available for this enum.</summary>");
                Write("public static extern EnumItem[] GetEnumItems();");
                PopIndent();
                Write("}");

                if (rbxEnum != rbxEnums.Last())
                    Write();
            }

            PopIndent();
            Write("}");
            WriteFile();
        }
    }
}