namespace TypeGenerator.Generators
{
    internal sealed class EnumGenerator : Generator
    {
        public EnumGenerator(string filePath, ReflectionMetadataReader reflectionMetadata)
            : base(filePath, reflectionMetadata) { }

        public void Generate(APITypes.Enum[] rbxEnums)
        {
            Write("// THIS FILE IS AUTOMATICALLY GENERATED AND SHOULD NOT BE EDITED MANUALLY!");
            Write("// GENERATED ROBLOX ENUMS");
            Write();

            Write("namespace Roblox.Enum");
            Write("{");
            PushIndent();
            foreach (var rbxEnum in rbxEnums)
            {
                var enumTypeName = rbxEnum.Name;
                var enumItems = rbxEnum.Items;
                Write($"public static class {enumTypeName}");
                Write("{");
                PushIndent();
                Write("public interface Type : EnumItem");
                Write("{");
                Write("}");
                Write();
                foreach (var item in enumItems)
                {
                    Write($"public static Type {item.Name} {{ get; }} = null!;");
                }
                Write();
                Write("/// <summary>Returns an array of all <see cref=\"EnumItem\"/> options available for this enum.</summary>");
                Write("public static EnumItem[] GetEnumItems()");
                Write("{");
                PushIndent();
                Write("return null!;");
                PopIndent();
                Write("}");
                PopIndent();
                Write("}");

                if (rbxEnum != rbxEnums.Last())
                {
                    Write();
                }
            }

            PopIndent();
            Write("}");
            WriteFile();
        }
    }
}