using static TypeGenerator.Constants;
using Enum = TypeGenerator.APITypes.Enum;

namespace TypeGenerator.Generators;

internal sealed class EnumGenerator(string filePath, ReflectionMetadataReader reflectionMetadata)
    : Generator(filePath, reflectionMetadata)
{
    public void Generate(Enum[] rbxEnums)
    {
        Write("// THIS FILE IS AUTOMATICALLY GENERATED AND SHOULD NOT BE EDITED MANUALLY!");
        Write("// GENERATED ROBLOX ENUMS");
        Write();
        Write("namespace Roblox.Enum;");
        Write();

        for (var i = 0; i < rbxEnums.Length; i++) GenerateEnum(rbxEnums[i], i == rbxEnums.Length - 1);

        WriteFile();
    }

    private void GenerateEnum(Enum rbxEnum, bool isLast)
    {
        var enumTypeName = rbxEnum.Name;
        var enumItems = rbxEnum.Items;
        Write($"public abstract class {enumTypeName} : EnumItem");
        Write("{");
        PushIndent();
        Write("extern string EnumItem.Name { get; }");
        Write("extern uint EnumItem.Value { get; }");
        Write("extern string EnumItem.EnumType { get; }");
        Write("public extern bool IsA<T>(string name) where T : Enum;");
        Write();

        var blacklistedItems = ENUM_BLACKLIST.GetValueOrDefault(rbxEnum.Name) ?? [];
        foreach (var item in enumItems)
        {
            if (blacklistedItems.Contains(item.Name)) continue;
            Write($"public static extern {enumTypeName} {item.Name} {{ get; }}");
        }

        Write();
        Write("/// <summary>Returns an array of all <see cref=\"EnumItem\"/> options available for this enum.</summary>");
        Write("public static extern EnumItem[] GetEnumItems();");
        PopIndent();
        Write("}");

        if (isLast) return;
        Write();
    }
}